version: "3"

services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: example 
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '8080:8080'
  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
      - '${DOCUMENT_ROOT-../chatFinder/public}:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes: 
      - '${DOCUMENT_ROOT-../chatFinder}:/usr/src/app'
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000
  redis:
    container_name: 'redis-container'
    image: redis:latest
    ports:
      - "6379:6379"
